version: "3.7"
services:
  cadvisor:
    image: google/cadvisor
    ports:
     - 8080:8080
    volumes:
     - /var/run:/var/run:rw
     - /sys:/sys:ro
     - /:/rootfs:ro
     - /var/lib/docker/:/var/lib/docker:ro
